version: '2'
services:
  zookeeper:
    image: enow/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
    environment:
      - SERVER_ID=1
      - ADDITIONAL_ZOOKEEPER_1=server.1=0.0.0.0:2888:3888
  nimbus:
    image: enow/storm-nimbus
    restart: always
    ports:
      - "6627:6627"
      - "22"
     depends_on:
      - zookeeper
  supervisor:
    image: enow/storm-supervisor
    restart: always
    ports:
      - "22"
    depends_on:
      - nimbus
  ui:
    image: enow/storm-ui
    restart: always
    ports:
      - "8080:8080"
      - "22"
    depends_on:
      - nimbus
  kafka:
    image: enow/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "test:3:1,onlytest:3:1"
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  topology:
    build: ./submitter
    command: -c nimbus.host=nimbus jar ./topology.jar com.enow.storm.TestTopologyStaticHosts Enow
    depends_on:
      - nimbus
networks:
  default:
    external:
      name: storm
